config/routes.rb
Toothbrush::Application.routes.draw do
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :view, :silver if user.has_role? :silver
      can :view, :gold if user.has_role? :gold
      can :view, :platinum if user.has_role? :platinum
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :stripe_token, :coupon
  attr_accessor :stripe_token, :coupon
  before_save :update_stripe
  before_destroy :cancel_subscription

  def update_plan(role)
    self.role_ids = []
    self.add_role(role.name)
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      customer.update_subscription(:plan => role.name)
    end
    true
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to update your subscription. #{e.message}."
    false
  end
  
  def update_stripe
    return if email.include?(ENV['ADMIN_EMAIL'])
    return if email.include?('@example.com') and not Rails.env.production?
    if customer_id.nil?
      if !stripe_token.present?
        raise "Stripe token not present. Can't create account."
      end
      if coupon.blank?
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name
        )
      else
        customer = Stripe::Customer.create(
          :email => email,
          :description => name,
          :card => stripe_token,
          :plan => roles.first.name,
          :coupon => coupon
        )
      end
    else
      customer = Stripe::Customer.retrieve(customer_id)
      if stripe_token.present?
        customer.card = stripe_token
      end
      customer.email = email
      customer.description = name
      customer.save
    end
    self.last_4_digits = customer.cards.data.first["last4"]
    self.customer_id = customer.id
    self.stripe_token = nil
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "#{e.message}."
    self.stripe_token = nil
    false
  end
  
  def cancel_subscription
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      unless customer.nil? or customer.respond_to?('deleted')
        if customer.subscription.status == 'active'
          customer.cancel_subscription
        end
      end
    end
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to cancel your subscription. #{e.message}."
    false
  end
  
  def expire
    UserMailer.expire_email(self).deliver
    destroy
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    case current_user.roles.first.name
      when 'admin'
        users_path
      when 'silver'
        content_silver_path
      when 'gold'
        content_gold_path
      when 'platinum'
        content_platinum_path
      else
        root_path
    end
  end
  
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  before_filter :authenticate_user!
  
  def silver
    authorize! :view, :silver, :message => 'Access limited to Silver Plan subscribers.'
  end
  
  def gold
    authorize! :view, :gold, :message => 'Access limited to Gold Plan subscribers.'
  end

  def platinum
    authorize! :view, :platinum, :message => 'Access limited to Platinum Plan subscribers.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    @plan = params[:plan]
    if @plan && ENV["ROLES"].include?(@plan) && @plan != "admin"
      super
    else
      redirect_to root_path, :notice => 'Please select a subscription plan below.'
    end
  end

  def update_plan
    @user = current_user
    role = Role.find(params[:user][:role_ids]) unless params[:user][:role_ids].nil?
    if @user.update_plan(role)
      redirect_to edit_user_registration_path, :notice => 'Updated plan.'
    else
      flash.alert = 'Unable to update plan.'
      render :edit
    end
  end

  def update_card
    @user = current_user
    @user.stripe_token = params[:user][:stripe_token]
    if @user.save
      redirect_to edit_user_registration_path, :notice => 'Updated card.'
    else
      flash.alert = 'Unable to update card.'
      render :edit
    end
  end

  private
  def build_resource(*args)
    super
    if params[:plan]
      resource.add_role(params[:plan])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    role = Role.find(params[:user][:role_ids]) unless params[:user][:role_ids].nil?
    params[:user] = params[:user].except(:role_ids)
    if @user.update_attributes(params[:user])
      @user.update_plan(role) unless role.nil?
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/content/gold.html.slim
h1 Content#gold
p Find me in app/views/content/gold.html.slim

app/views/content/platinum.html.slim
h1 Content#platinum
p Find me in app/views/content/platinum.html.slim

app/views/content/silver.html.slim
h1 Content#silver
p Find me in app/views/content/silver.html.slim

app/views/home/index.html.slim
#welcome.hero-unit.span7
  h1 Membership Site
  h3 Learn to build a successful subscription site.
.row.span8.plans
  .span2.well
    .plan
      h2 Silver
    ul.unstyled
      li One lesson a month
    h3 $9/month
    = link_to 'Subscribe', new_user_registration_path(:plan => 'silver'), :class => 'btn btn-primary'
  .span2.well.featured
    .plan.featured-plan
      h2 Gold
    ul.unstyled
      li Ten lessons a month
    h3 $19/month
    = link_to 'Subscribe', new_user_registration_path(:plan => 'gold'), :class => 'btn btn-primary'
  .span2.well
    .plan
      h2 Platinum
    ul.unstyled
      li Thirty lessons a month
    h3 $29/month
    = link_to 'Subscribe', new_user_registration_path(:plan => 'platinum'), :class => 'btn btn-primary'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "error"}" 
    a.close[data-dismiss="alert"]
      | ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
= link_to "Rails Stripe Membership Saas", root_path, :class => 'brand'
ul.nav
  - if user_signed_in?
    li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      li
        = link_to 'Admin', users_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Toothbrush'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Toothbrush'}"
    == stylesheet_link_tag "application", :media => "all"
    == javascript_include_tag "application"
    == csrf_meta_tags
  body
    / application layout styled for Bootstrap 2.3
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        .content
          .row
            .span12
              == render 'layouts/messages'
              == yield
          footer

app/views/users/_user.html.slim
.modal id="role-options-#{user.id}" style=("display: none;") 
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      a.close data-dismiss="modal"  ×
      h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      a.btn data-dismiss="modal" href="#"  Close

app/views/users/index.html.slim
h3 Users
.span8
  table.table.table-condensed
    thead
      tr
        th Username
        th Email
        th Registered
        th Role
        th
        th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, user
          td= user.email
          td= user.created_at.to_date
          td= user.roles.first.name.titleize unless user.roles.first.nil?
          td
            a.btn.btn-mini data-toggle="modal" href="#role-options-#{user.id}" type="button"  Change role
            = render user
          td= link_to("Delete user", user_path(user), :data =>   confirm=("Are you sure?" ) , :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.slim
h3 User
p
  | User: #{@user.name}
p
  | Email: #{@user.email if @user.email}